rarity_map = {
    1: "⚪ Common",
    2: "⭐ Basic",
    3: "⚡ Standard",
    4: "🟢 Medium",
    5: "🟣 Rare",
    6: "🟡 Legendary",
    7: "🌟 Uncommon",
    8: "💮 Special Edition",
    9: "🍃 Ghibli",
    10: "⚜ Royal",
    11: "🎃 X Verse",
    12: "🌌 Cosmic",
    13: "🔮 Limited Edition",
    14: "❄️ Ethereal",
    15: "🔱 Ultimate",
    16: "♾️ Immortal Teams",
    17: "🧿 Premium",
    18: "👑 Supreme"
}

RARITY_NAMES = [
    "⚪ Common",
    "⭐ Basic",
    "⚡ Standard",
    "🟢 Medium",
    "🟣 Rare",
    "🟡 Legendary",
    "🌟 Uncommon",
    "💮 Special Edition",
    "🍃 Ghibli",
    "⚜ Royal",
    "🎃 X Verse",
    "🌌 Cosmic",
    "🔮 Limited Edition",
    "❄️ Ethereal",
    "🔱 Ultimate",
    "♾️ Immortal Teams",
    "🧿 Premium",
    "👑 Supreme"
]

rarity_map2 = {
    "⚪ Common": "⚪",
    "⭐ Basic": "⭐",
    "⚡ Standard": "⚡",
    "🟢 Medium": "🟢",
    "🟣 Rare": "🟣",
    "🟡 Legendary": "🟡",
    "🌟 Uncommon": "🌟",
    "💮 Special Edition": "💮",
    "🍃 Ghibli": "🍃",
    "⚜ Royal": "⚜",
    "🎃 X Verse": "🎃",
    "🌌 Cosmic": "🌌",
    "🔮 Limited Edition": "🔮",
    "❄️ Ethereal": "❄️",
    "🔱 Ultimate": "🔱",
    "♾️ Immortal Teams": "♾️",
    "🧿 Premium": "🧿",
    "👑 Supreme": "👑"
}