rarity_map = {
    1: "⚪️ Common",
    2: "🟣 Rare",
    3: "🟡 Legendary",
    4: "🟢 Medium",
    5: "💮 Special Edition",
    6: "🔮 Limited Edition",
    7: "🎐 Celestial",
    8: "💖 Valentine",
    9: "🎃 Halloween",
    10: "❄️ Winter",
    11: "💸 Expensive",
    12: "💌 AMV",
    13: "🏖 Summer",
    14: "🧬 X-Verse",
    15: "✨ Neon",
    16: "⚜ Royal",
    17: "🎨 Holi Addition",
    18: "🥵 Erotic"
}

RARITY_NAMES = [
    "⚪️ Common",
    "🟣 Rare",
    "🟡 Legendary",
    "🟢 Medium",
    "💮 Special Edition",
    "🔮 Limited Edition",
    "🎐 Celestial",
    "💖 Valentine",
    "🎃 Halloween",
    "❄️ Winter",
    "💸 Expensive",
    "💌 AMV",
    "🏖 Summer",
    "🧬 X-Verse",
    "✨ Neon",
    "⚜ Royal",
    "🎨 Holi Addition",
    "🥵 Erotic"
]

rarity_map2 = {
    "⚪️ Common": "⚪️",
    "🟣 Rare": "🟣",
    "🟡 Legendary": "🟡",
    "🟢 Medium": "🟢",
    "💮 Special Edition": "💮",
    "🔮 Limited Edition": "🔮",
    "🎐 Celestial": "🎐",
    "💖 Valentine": "💖",
    "🎃 Halloween": "🎃",
    "❄️ Winter": "❄️",
    "💸 Expensive": "💸",
    "💌 AMV": "💌",
    "🏖 Summer": "🏖",
    "🧬 X-Verse": "🧬",
    "✨ Neon": "✨",
    "⚜ Royal": "⚜",
    "🎨 Holi Addition": "🎨",
    "🥵 Erotic": "🥵"
}
